# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170820_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Roboczy'), ('published', 'Publiczny')], default='draft', max_length=10),
        ),
    ]
