# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_photo',
            field=models.FileField(default='/media/author_photo/575786-E94.jpg', upload_to='author_photo'),
        ),
    ]
