# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170820_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_photo',
        ),
    ]
